<#import "tpl/mainpage.ftlh" as mp>
<@mp.page>
<form action="/login" method="post">
    <input type="hidden" name="_csrf" value="${_csrf.token}" />
    <div><label> User Name : <input type="text" name="username"/> </label></div>
    <div><label> Password : <input type="password" name="password"/> </label></div>
    <div><input type="submit" value="Sign in"/></div>
</form>
<a href="/registration">Registration</a>
</@mp.page>